#!/bin/bash

function compile {
  babel src/ --inline-source-maps --out-dir dist/
}

function lint {
  jshint src test
}

function tests {
  mocha --compilers js:babel-register
}

function publish {
  ./run compile && ./run lint && npm publish
}

"$@"
